name: Sync ASG State

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to sync ASG for'
        required: true
        default: prod

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ap-south-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.13.5

      - name: Set environment variable
        run: echo "ENV=${{ github.event.inputs.environment }}" >> $GITHUB_ENV
          
      - name: Terraform Init
        working-directory: envs/${{ env.ENV }}
        run: terraform init -input=false
        
      - name: Sync ASG state
        working-directory: envs/${{ env.ENV }}
        run: |
          chmod +x ./sync-asg-state.sh
          ./sync-asg-state.sh
    
      # Terraform Plan
      - name: Terraform Plan
        working-directory: envs/${{ env.ENV }}
        run: terraform plan -out=tfplan

      # Terraform Apply
      - name: Terraform Apply
        working-directory: envs/${{ env.ENV }}
        run: terraform apply -auto-approve tfplan
